import http.server

class SimpleHTTPRequestHandler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        # Set the content type as HTML
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()

        # HTML content generated by Python
        self.wfile.write(b"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Python-Generated Webpage</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    background-color: #f4f4f4;
                    margin: 0;
                    padding: 0;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    height: 100vh;
                    color: #333;
                }
                .container {
                    text-align: center;
                }
                h1 {
                    font-size: 36px;
                    color: #333;
                }
                p {
                    font-size: 18px;
                }
                button {
                    padding: 10px 20px;
                    font-size: 16px;
                    cursor: pointer;
                    margin-top: 20px;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Welcome to My Python-Generated Webpage!</h1>
                <p>This page was created dynamically using Python.</p>
                <button onclick="alert('You clicked the button!')">Click Me</button>
            </div>
        </body>
        </html>
        """)

# Run the server
if __name__ == '__main__':
    server_address = ('', 8000)  # Empty address and port 8000
    httpd = http.server.HTTPServer(server_address, SimpleHTTPRequestHandler)
    print("Server running on http://localhost:8000/")
    httpd.serve_forever()
